### ISSUE TITLE
Local access stops randomly working

### ISSUE THREAD

**Issue by Schwebebahn** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#131]
After some time, the Tahoma Switch Box is unavailable in my local network. Unavailable in my Home Assistant (Overkiz / Local API) and also in Apple Homekit. Can't ping and did not get an answer when asking for the version by curl, but still works with the cloud app. When I reboot the device, it works for some time. My WiFi is from UniFi, when I force the switch to connect to an other access point, it is also working for some time. So, could it be:
a) That the switch is blocking access from local network?
b) That UniFi is related to the problem?

The IP of the switch is static and all devices are in the same subnet.

**Comment by iMicknl** [comment]
I have the same issue. @llavorel-somfy, @vhenriet-sfy what details can we provide that can help debug this?

**Comment by BernoldNL** [comment]
For me, it hasn't stopped working (yet), but I did notice that after a while the response time gets longer and longer. After rebooting the TaHoma Switch, reponse times are lower again. I think this was introduced with version 2024.1.4-11 , because I have not noticed it before.

**Comment by llavorel-somfy** [comment]
Hi @iMicknl 

Would you be able to share with us you Serial Number ? 

Are you able to detect at which date and time the disconnection occured ?

**Comment by wcastand** [comment]
Same here, was working fine, i had to move the box so i unplugged and since then impossible to add to homekit or home assistant or use the local api. the only thing that works is the cloud api.

**Comment by Schwebebahn** [comment]
You can have my serial number if it helps, but not here in public :)
Based on my monitoring, it started working on 29.05. 22:20 and stopped 30.05. 08:55. (UTC/GMT +2)

Could is always local, only the local access by Home Kit and Home Assistant and PING is not working.

<img width="1372" alt="Switch traffic" src="https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/assets/96775010/07ee0277-6b1f-403e-947f-36e6b4e63b74">

**Comment by llavorel-somfy** [comment]
@Schwebebahn  Can you email it at developer@somfy.com ?

**Comment by Schwebebahn** [comment]
done

**Comment by Schwebebahn** [comment]
fyi: our internet was down the last 2 days, so the box was not online.

**Comment by JTT22** [comment]
I have the same issue, tried to do various changes in the unifi config like disable security etc that could interfere but to no help. connection goes on and off every few minutes in the HA log. using xx.local adress and unable to connect via ip.

**Comment by nickngsr** [comment]
We've seen this happen on two of our units now, local api refuses to connect until the Switch is power cycled

**Comment by eekhoorn** [comment]
For me the same. This was today in the domoticz log:
`2024-06-19 03:17:31.201 Error: Somfy: Failed to request data: HTTPSConnectionPool(host='xxxxxxxx.local', port=8443): Max retries exceeded with url: /enduser-mobile-web/1/enduserAPI/setup/devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5dcf8058>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-19 03:17:51.039 Error: Somfy: Call to function 'onHeartbeat' failed, exception details:
2024-06-19 03:17:51.054 Error: Somfy: Traceback (most recent call last):
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 612, in onHeartbeat
2024-06-19 03:17:51.054 Error: Somfy: _plugin.onHeartbeat()
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 308, in onHeartbeat
2024-06-19 03:17:51.054 Error: Somfy: filtered_devices = self.tahoma.get_devices()
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/tahoma_local.py", line 189, in get_devices
2024-06-19 03:17:51.054 Error: Somfy: filtered_list = utils.filter_devices(response.json())
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/utils.py", line 17, in filter_devices
2024-06-19 03:17:51.054 Error: Somfy: logging.debug("filter_devices: Device name: "+device["label"]+" Device class: "+device["definition"]["uiClass"])`

**Comment by iMicknl** [comment]
@eekhoorn if you see the same in your Domoticz logs, it might be a hub problem... Do you run Domoticz and HA on the same machine?

**Comment by nickngsr** [comment]
I've had this happen on a few units now, they flat our refuse connections on port 8443 until rebooted, @llavorel-somfy is there any update on this?

**Comment by bellef** [comment]
Same is happening to me for a few months now.
Even when I try to negociate a token using Postman, I get a `Error: connect ECONNREFUSED 217.182.125.204:80` on the `ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login` endpoint (from Europe/France)

**Comment by nickngsr** [comment]
@bellef I don't believe that's the same problem we're seeing as it's local comms to the tahoma on port 8443 that's stops working for us.

For your token issue will need to make sure you are using https on the cloud API (would be on port 443 not 80)

**Comment by nickngsr** [comment]
We've just had another unit do this. The only way to get the local API back up and running again was to power down the device for ~5 minutes and power it up again. If you did a fast power cycle it would still not connect.

Just to re-iterate we have no issues with access tokens, the unit refuses any connection on port 8443.

**Comment by gardz** [comment]
Exact same issue just hit me today too after a power outage. Once the Somfy Connexoon hub came back online it's no longer listening on 8443 and cannot use the local API. Only option is the power cycle the device again. I'm running "box version 2025.3.2-87" and connected via Ethernet.

**Comment by llavorel-somfy** [comment]
Hi @nickngsr 

We are working on it, specifically for https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/139, we do have a solution. (However we cannot guarantee it covers 100% of cases yet). 
I don't have an ETA for the moment.

**Comment by llavorel-somfy** [comment]
Anyone still facing the issue after last September update ?

**Comment by 1337-gitter** [comment]
I'm currently on firmware version 2026.1.3-3. I can confirm that the stability increased after the last updates. Since then, I didn't observe the case that local access stopped working _completely_ (which was the case before; power-cycle required to resolve the situation).
However, I still notice _sporadic_ connectivity loss with the device. I'm using an automation in Home Assistant which notifies me as soon as the device gets unavailable. This happens sometimes several times a day. I currently don't know how long these outages persist but I assume that control commands which are sent within this time frame are lost.

**Comment by llavorel-somfy** [comment]
Thank you @1337-gitter for the feedback !

As you say this can be linked to connectivity loss which is a different issue than the initial one.
