### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by sanderlv** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#145]
This night my internet provider "updated" my modem. If things would not work I had to restart it in the morning. All was fine but not my Overkiz connection from within homeassistant.

This integration worked very well before the update this night. 
This morning, it did not... when "reloading" the integration nothing happened and "error-ed" so I decided to remove it and re-add it.

Now I am facing issues when I try to include it in HA:
![image](https://github.com/user-attachments/assets/c5719c4d-cf96-4dd5-9339-1bd876f85ef5)

I tried:
- restarting all (Somfy box, HA, router)
- using IP address instead of name
- with/without "verify ssl certificate"
- I can Ping the box

Nothing changed on the somfy Tahoma box.

Username and password are 100% correct as I can loging on "my somfy".

What's next to check or do?

**Comment by sanderlv** [comment]
Some additional info:

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fa714eb0ad0>, '/usr/local/lib/python3.12/site-packages/pyoverkiz/overkiz-root-ca-2048.crt', None, None) inside the event loop by integration 'overkiz' at homeassistant/components/overkiz/config_flow.py, line 404: local_client = OverkizClient( (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+overkiz%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/usr/src/homeassistant/homeassistant/components/overkiz/config_flow.py", line 232, in async_step_local user_input = await self.async_validate_input(user_input) File "/usr/src/homeassistant/homeassistant/components/overkiz/config_flow.py", line 69, in async_validate_input user_input[CONF_TOKEN] = await self._create_local_api_token( File "/usr/src/homeassistant/homeassistant/components/overkiz/config_flow.py", line 404, in _create_local_api_token local_client = OverkizClient(

**Comment by sanderlv** [comment]
Created an issue here as well: https://github.com/home-assistant/core/issues/129076

**Comment by sanderlv** [comment]
It seems after trying multiple multiple times it now works....
