### ISSUE TITLE
Can't control Radiator Valve

### ISSUE THREAD

**Issue by AdyRock** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#53]
If I send commands to a radiator valve using the new local API, an error message is returned: "failureType": "INVALID_COMMAND". Sending the same commands using the unofficial cloud API works fine and queues the message for when the valve next wakes up.

Note: I can read the valve status values locally and get events locally.

**Comment by vhenriet-sfy** [comment]
Hi @AdyRock,

Could you give us the device description and the payload of the request that execute the command?

**Comment by AdyRock** [comment]
Hi @vhenriet-sfy,
This is the snippet of the device information
```
          "attributes": [
            {
              "type": 3,
              "name": "core:Manufacturer",
              "value": "Somfy"
            },
            {
              "type": 3,
              "name": "core:FirmwareRevision",
              "value": "5145198A12"
            }
          ],
          "enabled": true,
          "controllableName": "io:HeatingValveIOComponent",

```

This is a typical payload:
```
{
  "label": "Rad Valve - setDerogation  - Homey",
  "actions": [
    {
      "deviceURL": "deviceUrl in here",
      "commands": [
        {
          "name": "setDerogation",
          "parameters": [
            "15.5",
            "next_mode"
          ]
        }
      ]
    }
  ]
}
```

**Comment by AdyRock** [comment]
When I sent the command via the unofficial API, I get the following events in my log:
```
{
  "time": "2022-09-01T14:57:00.185Z",
  "elapsed": 0.694,
  "source": "Fetching Events",
  "data": {
    "message": "Complete",
    "stack": [
      {
        "timestamp": 1662044216359,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "label": "Rad Valve - setDerogation  - Homey",
        "metadata": "",
        "type": 1,
        "subType": 1,
        "actions": [
          {
            "deviceURL": "device url here",
            "commands": [
              {
                "name": "setDerogation",
                "parameters": [
                  {
                    "type": 2,
                    "value": "15.5"
                  },
                  {
                    "type": 3,
                    "value": "next_mode"
                  }
                ]
              }
            ]
          }
        ],
        "source": "mobile:tool",
        "owner": "me",
        "name": "ExecutionRegisteredEvent"
      },
      {
        "timestamp": 1662044216359,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "NOT_TRANSMITTED",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "INITIALIZED",
        "timeToNextState": 0,
        "name": "ExecutionStateChangedEvent"
      },
      {
        "timestamp": 1662044216359,
        "gatewayId": "xxxx-xxxx-xxxx",
        "name": "GatewaySynchronizationStartedEvent"
      },
      {
        "timestamp": 1662044216361,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "TRANSMITTED",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "NOT_TRANSMITTED",
        "timeToNextState": 0,
        "name": "ExecutionStateChangedEvent"
      },
      {
        "timestamp": 1662044216362,
        "gatewayId": "xxxx-xxxx-xxxx",
        "name": "GatewaySynchronizationEndedEvent"
      },
      {
        "timestamp": 1662044216947,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "IN_PROGRESS",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "TRANSMITTED",
        "timeToNextState": 0,
        "name": "ExecutionStateChangedEvent"
      },
      {
        "timestamp": 1662044216949,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "QUEUED_GATEWAY_SIDE",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "IN_PROGRESS",
        "timeToNextState": -1,
        "name": "ExecutionStateChangedEvent"
      },
      {
        "timestamp": 1662044216951,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "IN_PROGRESS",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "QUEUED_GATEWAY_SIDE",
        "timeToNextState": 0,
        "name": "ExecutionStateChangedEvent"
      },
      {
        "timestamp": 1662044216954,
        "setupOID": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "execId": "f98e1c24-98e4-e192-4445-e137ce80c79b",
        "newState": "QUEUED_GATEWAY_SIDE",
        "ownerKey": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": 1,
        "subType": 1,
        "oldState": "IN_PROGRESS",
        "timeToNextState": -1,
        "name": "ExecutionStateChangedEvent"
      }
    ]
  }
},

```

But if I send it via the new local API it just returns  "failureType": "INVALID_COMMAND".

**Comment by AdyRock** [comment]
Any news on this one?

**Comment by Bl4ckfi3lds** [comment]
Hello,
Same issue for me with the local API. I can't set a temperature for my IO thermostat.
I try to send the following action to https://{local_tahoma_ip}:8443/enduser-mobile-web/1/enduserAPI/exec/apply

{
    "label": "Thermostat io",
    "actions": [
        {
            "deviceURL": "io://2203-1910-9117/4438026#1",
            "commands": [
                {
                    "name": "setDerogation",
                    "parameters": [
                        "20.0",
                        "further_notice"
                    ]
                }
            ]
        }
    ]
}

I get a execution ID as a response but nothing append, if I try to check the status with a GET on : https://{local_tahoma_ip}:8443/enduser-mobile-web/1/enduserAPI/exec/current I get an empty list...

Can you help me modify my set temperature locally ?

**Comment by legantois** [comment]
Hello Mr llavorel-somfy

It seems that you are the magician here. Could you tell your community for how many years more we are going to be waiting for an answer from your side ?

Thermostatic Valve are recognised using this local API. we can all see them 
They are running asynchronously on battery (one update every 10 mins or so)
For this reason Somfy cloud base infrastructure is piloting them specifically

could you please provide information on this simple cloud logic so that we can easily replicate it in our own infrastructure ?

of course it could be ideal if this logic was implemented in your boxes (but as i do not believe in miracles detailed info on the chaining of commands will be enough

Many thanks for your help

message from hundreds of users that bought your expensive valves and your expensive boxes and would like to be treated as customers

**Comment by llavorel-somfy** [comment]
Released with version 2025.5.5-9

**Comment by AdyRock** [comment]
Ooh, great, I will adapt my code and test it ASAP. 
Thank you.

**Comment by legantois** [comment]
It seems not working so well

we can view when changing for instance required temperature on the device, it update on HA

But when asking via HA to change required temperature, sometimes it works and sometimes it does not... (wether by automation or using thermostat feature and lovelace)

anyone having the same issue ?

What do you need to debug ?

**Comment by legantois** [comment]
Debug mode if it helps. Tried several times to update the required temperature, then checked on the device the temperature. Did not change...

2025-11-26 22:19:11.841 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.138 seconds (success: True)
2025-11-26 22:19:16.873 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.168 seconds (success: True)
2025-11-26 22:19:21.775 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.071 seconds (success: True)
2025-11-26 22:19:26.794 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.089 seconds (success: True)
2025-11-26 22:19:31.913 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.209 seconds (success: True)
2025-11-26 22:19:33.972 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.COMMAND_EXECUTION_STATE_CHANGE: 'CommandExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='33ab8f17-08e4-4c34-8ff6-ea6df04d1bbb', device_url=io://****-****-9373/12500246#1, device_states=[], old_state=None, new_state=None)
2025-11-26 22:19:33.973 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.EXECUTION_STATE_CHANGED: 'ExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=[{'rank': 0, 'device_url': 'io://****-****-9373/12500246#1', 'failure_type': 'INVALID_COMMAND'}], failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='33ab8f17-08e4-4c34-8ff6-ea6df04d1bbb', device_url=None, device_states=[], old_state=<ExecutionState.INITIALIZED: 'INITIALIZED'>, new_state=<ExecutionState.FAILED: 'FAILED'>)
2025-11-26 22:19:33.973 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.158 seconds (success: True)
2025-11-26 22:19:36.103 DEBUG (MainThread) [homeassistant.components.overkiz] ZeroConf discovery detected gateway ****-****-9373 on gateway-****-****-9373.local. (_kizbox._tcp.local.)
2025-11-26 22:19:36.104 DEBUG (MainThread) [homeassistant.components.overkiz] ZeroConf discovery detected gateway ****-****-9373 on gateway-****-****-9373.local. (_kizboxdev._tcp.local.)
2025-11-26 22:19:36.921 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.026 seconds (success: True)
2025-11-26 22:19:41.731 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.COMMAND_EXECUTION_STATE_CHANGE: 'CommandExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='3fbfcbf4-0a05-40ea-85ff-b12cbd7c91ad', device_url=io://****-****-9373/12500246#1, device_states=[], old_state=None, new_state=None)
2025-11-26 22:19:41.732 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.EXECUTION_STATE_CHANGED: 'ExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=[{'rank': 0, 'device_url': 'io://****-****-9373/12500246#1', 'failure_type': 'INVALID_COMMAND'}], failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='3fbfcbf4-0a05-40ea-85ff-b12cbd7c91ad', device_url=None, device_states=[], old_state=<ExecutionState.INITIALIZED: 'INITIALIZED'>, new_state=<ExecutionState.FAILED: 'FAILED'>)
2025-11-26 22:19:41.732 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.027 seconds (success: True)
2025-11-26 22:19:46.767 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.063 seconds (success: True)
2025-11-26 22:19:51.744 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=io://****-****-9373/13174244#2, device_states=[EventState(name='core:TemperatureState', type=<DataType.FLOAT: 2>, value=20.5)], old_state=None, new_state=None)
2025-11-26 22:19:51.744 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.040 seconds (success: True)
2025-11-26 22:22:51.902 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.198 seconds (success: True)
2025-11-26 22:22:56.906 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.202 seconds (success: True)
2025-11-26 22:23:01.936 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.232 seconds (success: True)
2025-11-26 22:23:06.851 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.146 seconds (success: True)
2025-11-26 22:23:08.845 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.023 seconds (success: True)
2025-11-26 22:23:13.830 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.COMMAND_EXECUTION_STATE_CHANGE: 'CommandExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='4bb69bce-0a5e-4867-bd96-0c6989fce795', device_url=io://****-****-9373/12500246#1, device_states=[], old_state=None, new_state=None)
2025-11-26 22:23:13.831 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.EXECUTION_STATE_CHANGED: 'ExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=[{'rank': 0, 'device_url': 'io://****-****-9373/12500246#1', 'failure_type': 'INVALID_COMMAND'}], failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='4bb69bce-0a5e-4867-bd96-0c6989fce795', device_url=None, device_states=[], old_state=<ExecutionState.INITIALIZED: 'INITIALIZED'>, new_state=<ExecutionState.FAILED: 'FAILED'>)
2025-11-26 22:23:13.831 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.127 seconds (success: True)
2025-11-26 22:23:18.835 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=io://****-****-9373/12500246#2, device_states=[EventState(name='core:TemperatureState', type=<DataType.FLOAT: 2>, value=18.4)], old_state=None, new_state=None)
2025-11-26 22:23:18.835 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.132 seconds (success: True)
2025-11-26 22:23:28.709 INFO (MainThread) [backoff] Backing off execute_commands(...) for 0.8s (aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-****-****-9373.local:8443 ssl:False [MDNS lookup failed, Timeout while contacting DNS servers])
2025-11-26 22:23:28.721 INFO (MainThread) [backoff] Backing off fetch_events(...) for 0.3s (aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-****-****-9373.local:8443 ssl:False [MDNS lookup failed, Timeout while contacting DNS servers])
2025-11-26 22:23:32.044 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 8.340 seconds (success: True)
2025-11-26 22:23:32.606 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.COMMAND_EXECUTION_STATE_CHANGE: 'CommandExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='3ddd9b2c-ed9e-4161-ab69-69030219c470', device_url=io://****-****-9373/11549945#1, device_states=[], old_state=None, new_state=None)
2025-11-26 22:23:32.606 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.EXECUTION_STATE_CHANGED: 'ExecutionStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=[{'rank': 0, 'device_url': 'io://****-****-9373/11549945#1', 'failure_type': 'INVALID_COMMAND'}], failure_type_code=None, failure_type='INVALID_COMMAND', condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id='3ddd9b2c-ed9e-4161-ab69-69030219c470', device_url=None, device_states=[], old_state=<ExecutionState.INITIALIZED: 'INITIALIZED'>, new_state=<ExecutionState.FAILED: 'FAILED'>)
2025-11-26 22:23:32.606 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.062 seconds (success: True)
2025-11-26 22:23:37.722 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.017 seconds (success: True)
2025-11-26 22:23:42.800 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.096 seconds (success: True)
2025-11-26 22:23:47.718 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.015 seconds (success: True)
2025-11-26 22:23:52.741 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.036 seconds (success: True)
2025-11-26 22:23:57.743 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=io://****-****-9373/3785790#2, device_states=[EventState(name='core:TemperatureState', type=<DataType.FLOAT: 2>, value=26.3)], old_state=None, new_state=None)
2025-11-26 22:23:57.744 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.040 seconds (success: True)
2025-11-26 22:24:02.864 DEBUG (MainThread) [homeassistant.components.overkiz] Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=None, setupoid=_CountingAttr(counter=541, _default=None, repr=<function obfuscate_id at 0x7f8846648d60>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=io://****-****-9373/11549945#1, device_states=[EventState(name='core:BatteryLevelState', type=<DataType.INTEGER: 1>, value=37)], old_state=None, new_state=None)
2025-11-26 22:24:02.865 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.161 seconds (success: True)
2025-11-26 22:24:07.881 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.178 seconds (success: True)
2025-11-26 22:24:12.796 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.091 seconds (success: True)
2025-11-26 22:24:17.916 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.212 seconds (success: True)
2025-11-26 22:24:22.929 DEBUG (MainThread) [homeassistant.components.overkiz] Finished fetching device events data in 0.225 seconds (success: True)

**Comment by llavorel-somfy** [comment]
> It seems not working so well
> 
> we can view when changing for instance required temperature on the device, it update on HA
> 
> But when asking via HA to change required temperature, sometimes it works and sometimes it does not... (wether by automation or using thermostat feature and lovelace)
> 
> anyone having the same issue ?
> 
> What do you need to debug ?

Hi @legantois 

The valve is a sleepy device so when you send a new command it is in a queue until the valve wakes up to get it and send acquitment. You can try to :
1. Send command from HA
2. Wake up the valve (pressing one button) 
3. Verify on the valve that new temperature is taken 
4. Verify on HA

**Comment by legantois** [comment]
Hello LLavorel

I know this as i am using HA already with Cloud version (where behavior is the same)

when configured in the cloud version, it always work (from HA i can set a temperature, read sensor... both using lovelace and automation

When configure in the direct version
sometimes my automation works , sometimes not and when the automation does not work , the lovelace does not work neither

indeed i was not able to make it work again once it was not working (i had to remove batteries, and put them back to make them rewark again)

the log above was captured when it was not working, AND neither lovelace nor automation was able to modify the requested temperature

i put back the cloud version (as i need to heat my rooms) but i can make some trials to provide other logs if it can help

**Comment by AdyRock** [comment]
I have just tried to change the control to local for the radiator valve, but it is still not working, Any attempts to send commands are met with an code 400 via the local connection, but all is OK when using the cloud connection. So, I'm still not able to remove the cloud dependency from Homey Pro devices.
```
2025-12-28T12:58:10.415Z [err] Rad Valve: Local command failed (will try cloud), command: {
  "name": "setDerogation",
  "parameters": [
    "comfort",
    "further_notice"
  ]
}, error = Request failed with status code 400
Error: Request failed with status code 400
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at /app/node_modules/axios-cookiejar-support/lib/interceptors/response.js:83:25
    at new Promise (<anonymous>)
    at responseInterceptor (/app/node_modules/axios-cookiejar-support/lib/interceptors/response.js:82:9)
    at /app/node_modules/axios-cookiejar-support/lib/index.js:130:67
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async HttpHelper.post (/app/lib/HttpHelper.js:119:20)
    at async Tahoma.postWithReAuth (/app/lib/Tahoma.js:78:11)
    at async myApp.executeDeviceAction (/app/app.js:2001:19))
2025-12-28T12:58:10.420Z [err] Rad Valve: Command failed, no valid connections, command: {
  "name": "setDerogation",
  "parameters": [
    "comfort",
    "further_notice"
  ]
}
```

**Comment by llavorel-somfy** [comment]
@AdyRock  / @legantois  do you have a log of what the API is returning when you POST /exec/apply ?

**Comment by AdyRock** [comment]
The log is above. Basically, it returns error code 400.

**Comment by legantois** [comment]
I put full trace in debug mode above. Tell me what i need to do to provide an answer if this is not enough for you

**Comment by llavorel-somfy** [comment]
@AdyRock you receive INVALID_COMMAND as well ?

**Comment by AdyRock** [comment]
Axios is just reporting the error code 400 with no further information, which is effectively a bad request code returned from the server.

**Comment by llavorel-somfy** [comment]
I gave it another try and it is working for me : 

```
curl --location 'https://gateway-2001-****-2094.local:8443/enduser-mobile-web/1/enduserAPI/exec/apply' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "label": "Command vanne",
    "actions": [
        {
            "deviceURL": "io://2001-****-2094/5912588#1",
            "commands": [
                {
                    "name": "setDerogation",
                    "parameters": [
                        "comfort",
                        "further_notice"
                    ]
                }
            ]
        }
    ]
}'
```

response : 200 OK

```
{
    "execId": "6b32d4e9-****-****-9ae3-c5546f1e51c4"
}

```
